=== 4iz238/cviceni/04-xmlschema/faktura.xsd
<?xml version="1.0" encoding="iso-8859-2"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

 <xsd:element name="faktura">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="odberatel" type="subjektInfoTyp"/>
    <xsd:element name="dodavatel" type="subjektInfoTyp"/>
    <xsd:element ref="polozka" minOccurs='1' maxOccurs='unbounded'/>
   </xsd:sequence>
   <xsd:attribute name="cislo" type="cisloFakturyTyp" use="required"/>
   <xsd:attribute name="vystaveni" type="xsd:date" use="required"/>
   <xsd:attribute name="splatnost" type="xsd:date" use="required"/>
   <xsd:attribute name="vystavil" type="xsd:string"/>
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="subjektInfoTyp">
  <xsd:sequence>
   <xsd:element name="nazev" type="xsd:string"/>
   <xsd:element name="adresa" type="xsd:string"/>
   <xsd:element name="ico" type="icoTyp"/>
   <xsd:element name="dic" type="dicTyp"/>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:simpleType name="icoTyp">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="\d{10}"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="dicTyp">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="\d{3}-\d{10}"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="cisloFakturyTyp">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="\d{4}/\d{3}"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:element name="polozka">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="popis" type="xsd:string" minOccurs='0' maxOccurs='1'/>
    <xsd:element ref="cena"/>
    <xsd:element name="dph" type="dphTyp"/>
    <xsd:element name="ks" type="xsd:positiveInteger" minOccurs='0' maxOccurs='1'/>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="cena">
  <xsd:complexType>
   <xsd:simpleContent>
    <xsd:extension base="èástkaTyp">
     <xsd:attribute name="mena" type="kódMìnyTyp" />
    </xsd:extension>
   </xsd:simpleContent>
  </xsd:complexType>
 </xsd:element>

 <xsd:simpleType name="èástkaTyp">
  <xsd:restriction base="xsd:decimal">
   <xsd:minInclusive value="0" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="kódMìnyTyp">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="CZK"/>
   <xsd:enumeration value="DEM"/>
   <xsd:enumeration value="USD"/>
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="dphTyp">
  <xsd:restriction base="xsd:decimal">
   <xsd:enumeration value="22" />
   <xsd:enumeration value="5" />
  </xsd:restriction>
 </xsd:simpleType>

</xsd:schema>

=== 4iz238/cviceni/04-schema/faktura.xml
<?xml version="1.0" encoding="iso-8859-2"?>
<faktura xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xsi:noNamespaceSchemaLocation="faktura.xsd"
	       vystaveni="2000-02-02" splatnost="2000-02-16"
         cislo="2000/111">
  <odberatel>
    <nazev>Pouèená, a.s.</nazev>
    <adresa>©iroká 21, Praha 1, 110 00</adresa>
    <ico>0987654321</ico>
    <dic>007-0987654321</dic>
  </odberatel>
  <dodavatel>
    <nazev>XMLCompany, s.r.o.</nazev>
    <adresa>Dlouhá 12, Praha 1, 110 00</adresa>
    <ico>1234567890</ico>
    <dic>007-1234567890</dic>
  </dodavatel>
  <polozka>
    <popis>Analýza nasazení XML v podnikovém IS</popis>
    <cena>50000</cena>
    <dph>5</dph>
  </polozka>
  <polozka>
    <popis>XML Editor - 10 licencí</popis>
    <cena mena="USD">5000</cena>
    <dph>5</dph>
  </polozka> 
</faktura>
